feat: add create student endpoint
Muril0S4lvador/Orion-Bootcamp-Projeto-Civitas-Back pull request #8
Opened 2024-11-18 12:14 UTC by thaisbsts

2024-11-21 11:01 UTC, robsonfgomes-newrizon requested changes

2024-11-21 11:01 UTC, robsonfgomes-newrizon commented on package.json
> +    "deep-email-validator": "^0.1.21",
Fixar a versão das dependências.

2024-11-21 11:01 UTC, robsonfgomes-newrizon commented on src/controller/StudentController.ts
> +    /**
Sempre verificar os logs, a API está quebrando.
![image](https://github.com/user-attachments/assets/ff2117de-d10c-434c-ad84-0278e156c0f8)

2024-11-21 11:01 UTC, robsonfgomes-newrizon commented on src/controller/StudentController.ts
> +     *                 example: 111
Descreva os campos, o que seria "registration"?

2024-11-21 11:01 UTC, robsonfgomes-newrizon commented on src/controller/StudentController.ts
> +     *               schoolClassIdentifier:
O correto aqui seria o identificador da turma, o id do banco de dados.

2024-11-21 11:01 UTC, robsonfgomes-newrizon commented on src/controller/StudentController.ts
> +export class StudentController {
Esta ocorrendo erro no momento do cadastro, aparentemente não foi criada migration para adicionar o a coluna.
![image](https://github.com/user-attachments/assets/14c044af-92af-4c02-8d94-95c656612cd6)

2024-11-22 04:15 UTC, thaisbsts commented on src/controller/StudentController.ts
> +export class StudentController {
Oi! Testei aqui e não aconteceu esse erro que você mostrou... Até pensei que eu poderia ter modificado algo e não ter feito o commit, mas eu criei um novo repositório local e clonei dessa branch e deu tudo certo:

![image](https://github.com/user-attachments/assets/f4a00034-cdb8-455e-a437-2c8c9d49a7ca)

Resposta: 

![image](https://github.com/user-attachments/assets/c77186e9-317c-4bfd-a9d9-9cbe4c18e567)

2024-11-26 11:21 UTC, robsonfgomes-newrizon requested changes

2024-11-26 11:21 UTC, robsonfgomes-newrizon commented on migration/seeds/1730209097787-CreateUserTable.ts
Corrigir o erro ao rodar a aplicação.
![image](https://github.com/user-attachments/assets/f7ee28d7-35c9-4902-9d06-0b895eb4c1cd)

2024-11-26 11:21 UTC, robsonfgomes-newrizon commented on src/controller/StudentController.ts
> +     * /students:
![image](https://github.com/user-attachments/assets/0f670414-a6a1-43bb-8ba1-62614441e924)

2024-12-04 10:17 UTC, robsonfgomes-newrizon approved these changes

2024-12-05 01:39 UTC, merged